config/routes.rb
FacturacionRails::Application.routes.draw do
  devise_for :users

  root :to => "home#index"
   resources :users do
    resources :compras
    resources :pagos
    resources :pedidos
    resources :productos
    resources :facturas
    resources :inventarios
  end
end

app/models/compra.rb
class Compra < ActiveRecord::Base
  attr_accessible :id, :id_factura, :id_pedido, :id_user
end

app/models/factura.rb
class Factura < ActiveRecord::Base
  attr_accessible :fecha_exp, :id, :id_compra, :id_pedido
end

app/models/inventario.rb
class Inventario < ActiveRecord::Base
  attr_accessible :cantidad_existencia, :cantidad_vendida, :id
end

app/models/pago.rb
class Pago < ActiveRecord::Base
  attr_accessible :estado, :fecha_pago, :forma_pago, :id, :id_factura, :id_user
end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  attr_accessible :estado, :id, :id_user
end

app/models/producto.rb
class Producto < ActiveRecord::Base
  attr_accessible :estado, :id, :id_inventario, :nombre, :provedor
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
end

app/controllers/facturas_controller.rb
class FacturasController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pagos_controller.rb
class PagosController < ApplicationController
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventarios_helper.rb
module InventariosHelper
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="googlebot" content="index,follow"/>
    <meta name="author" content="Ing. Jonathan Olier Miranda"/>
    <meta name="copyright" content="Todos los derechos reservados por AltiviaOT.com"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="https://dl.dropbox.com/u/57960869/Altiviaot/bootstrap/bootstrap/css/altiviaot.css" rel="stylesheet">
	<style type="text/css">
		body { padding-top: 60px; padding-bottom: 40px; background-color:#f5f5f5; }
		footer { text-align:center; }
	</style>
	<link rel="stylesheet" type="text/css" href="https://dl.dropbox.com/u/57960869/Altiviaot/scrollbar.min.css" media="all">
	<link href="https://dl.dropbox.com/u/57960869/Altiviaot/bootstrap/bootstrap/css/altiviaot-responsive.css" rel="stylesheet">

	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
		<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<link rel="shortcut icon" href="https://dl.dropbox.com/u/57960869/Altiviaot/fav.ico">
	<title>Sistema de Facturacion</title>
  	<%= stylesheet_link_tag "application", :media => "all" %>
  	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<%=link_to "Facturacion", root_path, :class => "brand" %>
				<div class="nav-collapse">
					<% if not current_user %>
						<p class="navbar-text pull-right">
							<%=link_to "Iniciar Sesion", new_user_session_path %>
							o <%=link_to "Registrate", new_user_registration_path %>
						</p>
					<% else %>
						<ul class="nav">
							<li class="dropdown">
								<%=link_to "Productos", user_productos_path(current_user), :class => "dropdown-toggle", :data => { :toggle => "dropdown" } %>
								<ul class="dropdown-menu">
		                        	<li><%=link_to "New", new_user_producto_path(current_user) %></li>
		                        	<li><%=link_to "List", user_productos_path(current_user) %></li>
		                        </ul>
							</li>
							<li class="dropdown">
								<%=link_to "Pedidos", user_pedidos_path(current_user), :class => "dropdown-toggle", :data => { :toggle => "dropdown" } %>
								<ul class="dropdown-menu">
		                        	<li><%=link_to "New", new_user_pedido_path(current_user) %></li>
		                        	<li><%=link_to "List", user_pedidos_path(current_user) %></li>
		                        </ul>
							</li>
							<li class="dropdown">
								<%=link_to "Compras", user_compras_path(current_user), :class => "dropdown-toggle", :data => { :toggle => "dropdown" } %>
								<ul class="dropdown-menu">
		                        	<li><%=link_to "New", new_user_compra_path(current_user) %></li>
		                        	<li><%=link_to "List", user_compras_path(current_user) %></li>
		                        </ul>
							</li>
							<li class="dropdown">
								<%=link_to "Pagos", user_pagos_path(current_user), :class => "dropdown-toggle", :data => { :toggle => "dropdown" } %>
								<ul class="dropdown-menu">
		                        	<li><%=link_to "New", new_user_pago_path(current_user) %></li>
		                        	<li><%=link_to "List", user_pagos_path(current_user) %></li>
		                        </ul>
							</li>
						</ul>
							<!-- Bienvenido <%= current_user.email %> -->
							<ul class="nav pull-right">
								<li class="dropdown">
							    	<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i> User</a>
			                        <ul class="dropdown-menu">
			                        	<li><a href="#">Action</a></li>
							  			<li><%=link_to "Salir", destroy_user_session_path %></li>
			                        </ul>
							  	</li>
							</ul>
					<% end %>
				</div>
			</div>
		</div>
	</div>

	<div class="container-fluid">
		<p class="notice hide"><%= notice %></p>
		<p class="alert hide"><%= alert %></p>
		<%= yield %>
	  	<hr>
		<footer>
			<p>&copy; <a href="http://altiviaot.com/">AltiviaOT</a> 2012</p>
		</footer>
	</div>

  	<%= javascript_include_tag "application" %>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-transition.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-alert.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-modal.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-dropdown.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-scrollspy.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-tab.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-tooltip.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-popover.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-button.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-collapse.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-carousel.js"></script>
	<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-typeahead.js"></script>
	<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>

</body>
</html>